---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  - pip install docker-py
  - pip install flake8
  - pip install ansible-lint
before_script:
  - cd ../
  - mv ansible-postgresql postgresql
  - cd postgresql
script:
  - molecule test
