---
- name: Converge
  hosts: all
  roles:
    - role: ansible-postgresql
      postgresql_backup_gpg_private_key: "gpg/priv.asc"
      postgresql_backup_gpg_public_key: "gpg/pub.asc"
      postgresql_backup_gpg_trust_file: "gpg/trust-ultimate.txt"
      postgresql_enable_ssl: true
      postgresql_ssl_domain: "db.example.com"
      postgresql_ssl_ca_key: "{{ lookup('file', 'ssl/root.key') }}"
      postgresql_ssl_ca_cert: "{{ lookup('file', 'ssl/root.crt') }}"
      postgresql_users:
        - name: "molecule"
          pass: "myloginpass"
          encrypted: true
      postgresql_databases:
        - name: "molecule"
          owner: "molecule"
      postgresql_backup_database: "molecule"
      postgresql_backup_gpg_key_id: "53329157"
      postgresql_backup_gpg_pass: "ansibleisawesome"
      postgres_backup_gpg_opts: "{{ '' if ansible_lsb.major_release|int < 18 else '--pinentry-mode loopback' }}"
