---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
platforms:
  - name: ansible-postgresql-ubuntu-16.04
    image: solita/ubuntu-systemd:16.04
  - name: ansible-postgresql-ubuntu-18.04
    image: solita/ubuntu-systemd:18.04
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - destroy
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
