---
# should be reverted to Upstream when https://github.com/ANXS/postgresql/pull/475 gets merged 🤞
- name: ANXS.postgresql
  src: https://github.com/onaio/postgresql.git
  scm: git
  version: 26493277bf692128bf70b9a2a50d4a32b6db23f4
- name: onaio.gpg-import
  src: https://github.com/onaio/ansible-gpg-import.git
  scm: git
  version: master
- role: onaio.backup
  src: https://github.com/onaio/ansible-backup.git
  scm: git
  version: develop
- role: onaio.ssl-certificate
  src: https://github.com/onaio/ansible-ssl-certificate.git
  scm: git
  version: master
- role: onaio.monit
  src: https://github.com/onaio/ansible-monit.git
  scm: git
  version: master
